name: Q2 Workflow

on: [push]

permissions:
  contents: write

jobs:
  archive-q3-java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Créer Q3_archive_java.txt avec nom et contenu java
      run: |
        echo "Nom et prénom : Remi Viez" > Q3_archive_java.txt
        echo "" >> Q3_archive_java.txt
        cat Q3.java >> Q3_archive_java.txt

    - name: Commit et push le fichier Q3_archive_java.txt
      run: |
        git config user.name "RemiViez"
        git config user.email "remi.viez@univ-lehavre.fr"
        git add Q3_archive_java.txt
        git commit -m "Ajout de Q3_archive_java.txt avec nom et date" || echo "Rien à commit"
        git push
