name: Q4 Workflow

on: [push]

permissions:
  contents: write

jobs:
  archive-q4-java:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Définir la date au format JJ-MM-AAAA
      id: vars
      run: echo "DATE=$(date -d '+2 hour' +'%d-%m-%Y')" >> $GITHUB_ENV

    - name: Créer Q4_archive_DATE.txt avec nom, prénom et contenu Java
      run: |
        echo "Nom et prénom : Remi Vez" > Q4_archive_${{ env.DATE }}.txt
        echo "" >> Q4_archive_${{ env.DATE }}.txt
        cat Q4.java >> Q4_archive_${{ env.DATE }}.txt

    - name: Commit et push du fichier
      run: |
        git config user.name "RemiVez"
        git config user.email "remi.viez@univ-lehavre.fr"
        git add Q4_archive_${{ env.DATE }}.txt
        git commit -m "Ajout de Q4_archive_${{ env.DATE }}.txt" || echo "Rien à commit"
        git push
